services:
  - type: web
    name: fitvision-backend
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - key: SUPABASE_URL
        value: https://uezdldbsxoqzwpbslhob.supabase.co
      - key: SUPABASE_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlemRsZGJzeG9xendwYnNsaG9iIiwicm9sZSI6InNlcnZpY2Vfcm9sZSIsImlhdCI6MTc0ODIwMzI1NywiZXhwIjoyMDYzNzc5MjU3fQ.vD-ByIgei8Gnw_FSptAAw-zFFy7anDLA3YsvL2k_g1Y
